// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LayerTwoServiceClient is the client API for LayerTwoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LayerTwoServiceClient interface {
	// Get BlockNumber
	GetBlockNumber(ctx context.Context, in *GetBlockNumberRequest, opts ...grpc.CallOption) (*GetBlockNumberResponse, error)
	ProcessBlock(ctx context.Context, in *ProcessBlockRequest, opts ...grpc.CallOption) (*ProcessBlockResponse, error)
}

type layerTwoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLayerTwoServiceClient(cc grpc.ClientConnInterface) LayerTwoServiceClient {
	return &layerTwoServiceClient{cc}
}

func (c *layerTwoServiceClient) GetBlockNumber(ctx context.Context, in *GetBlockNumberRequest, opts ...grpc.CallOption) (*GetBlockNumberResponse, error) {
	out := new(GetBlockNumberResponse)
	err := c.cc.Invoke(ctx, "/api.LayerTwoService/GetBlockNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerTwoServiceClient) ProcessBlock(ctx context.Context, in *ProcessBlockRequest, opts ...grpc.CallOption) (*ProcessBlockResponse, error) {
	out := new(ProcessBlockResponse)
	err := c.cc.Invoke(ctx, "/api.LayerTwoService/ProcessBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LayerTwoServiceServer is the server API for LayerTwoService service.
// All implementations must embed UnimplementedLayerTwoServiceServer
// for forward compatibility
type LayerTwoServiceServer interface {
	// Get BlockNumber
	GetBlockNumber(context.Context, *GetBlockNumberRequest) (*GetBlockNumberResponse, error)
	ProcessBlock(context.Context, *ProcessBlockRequest) (*ProcessBlockResponse, error)
	mustEmbedUnimplementedLayerTwoServiceServer()
}

// UnimplementedLayerTwoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLayerTwoServiceServer struct {
}

func (UnimplementedLayerTwoServiceServer) GetBlockNumber(context.Context, *GetBlockNumberRequest) (*GetBlockNumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockNumber not implemented")
}
func (UnimplementedLayerTwoServiceServer) ProcessBlock(context.Context, *ProcessBlockRequest) (*ProcessBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessBlock not implemented")
}
func (UnimplementedLayerTwoServiceServer) mustEmbedUnimplementedLayerTwoServiceServer() {}

// UnsafeLayerTwoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LayerTwoServiceServer will
// result in compilation errors.
type UnsafeLayerTwoServiceServer interface {
	mustEmbedUnimplementedLayerTwoServiceServer()
}

func RegisterLayerTwoServiceServer(s grpc.ServiceRegistrar, srv LayerTwoServiceServer) {
	s.RegisterService(&LayerTwoService_ServiceDesc, srv)
}

func _LayerTwoService_GetBlockNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerTwoServiceServer).GetBlockNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.LayerTwoService/GetBlockNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerTwoServiceServer).GetBlockNumber(ctx, req.(*GetBlockNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayerTwoService_ProcessBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerTwoServiceServer).ProcessBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.LayerTwoService/ProcessBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerTwoServiceServer).ProcessBlock(ctx, req.(*ProcessBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LayerTwoService_ServiceDesc is the grpc.ServiceDesc for LayerTwoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LayerTwoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.LayerTwoService",
	HandlerType: (*LayerTwoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockNumber",
			Handler:    _LayerTwoService_GetBlockNumber_Handler,
		},
		{
			MethodName: "ProcessBlock",
			Handler:    _LayerTwoService_ProcessBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
